Repository DuckDuckStudio/Fufu_Dev_Tools, pull requests merged in 2024-09, with the labels that each got.

#12 feat: 议题与拉取请求模板
  .github/ISSUE_TEMPLATE/bug_feedback.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: DEV-已完成, DEV-开发分支合并, DEV-本地测试通过, 文档, 新功能

#13 feat: 退出代码与通知优化
  开发工具-源码/git/git连续尝试.py
  开发工具-源码/git/账号切换.py
  开发工具-源码/git/连续pull尝试.py
  开发工具-源码/git/连续push尝试.py
  开发工具-源码/总调用.py
  开发工具-源码/目录复制.pyw
Labels: DEV-已完成, DEV-开发分支合并, DEV-本地测试通过, 优化, 新功能

#18 feat: 自动打包发行版
  .github/workflows/auto-pack-releases.yml
  .gitignore
  pack.iss
  requirements.txt
  自动化脚本/Auto-Pack-Pyinstaller.py
Labels: DEV-已完成, DEV-开发分支合并, DEV-本地测试通过, 内部任务, 新功能
