Repository DuckDuckStudio/Fufu_Dev_Tools, pull requests merged in 2024-07, with the labels that each got.

#3 feat: 添加版本显示命令
  开发工具-winget/pack/Script/ffdev.py
Labels: DEV-开发分支合并, DEV-本地测试通过, DEV-PR中修复, 优化, 处理中, 新功能

#6 pref: 在某个仓库中执行git相关自动化时可以省去选择仓库目录的步骤
  开发工具/git/git连续尝试.py
  开发工具/git/连续pull尝试.py
  开发工具/git/连续push尝试.py
Labels: DEV-已完成, DEV-开发分支合并, DEV-本地测试通过, 优化, 新功能

#8 pref: 让git相关连续尝试工具的通知显示具体仓库
  开发工具/git/git连续尝试.py
  开发工具/git/连续pull尝试.py
  开发工具/git/连续push尝试.py
Labels: DEV-本地测试通过, 优化, 待发布
